### ISSUE TITLE
eqref doesn't work when we have an in-line equation

### ISSUE THREAD

**Issue by isboonto** [disberd/PlutoUtils.jl#3]
for example
md"""
$(eqref("eq1")) is with $x+2$
"""

**Comment by disberd** [comment]
Hi, This is more of a known problem of conflicts with LaTeX `$` and julia interpolation `$` when both of them appear in a markdown macro (see https://github.com/JuliaLang/julia/issues/36946 for example):
Using the alternative inline latex synthax with double backtick instead of `$` solves the issue (though at the moment the equation number is put in a newline of its own, but that should be fixable
![image](https://user-images.githubusercontent.com/12846528/141745221-cca5bada-3f8a-4c14-b135-16909f936781.png)
